### ISSUE TITLE
Its not clear what separators to use for Multiple tags. 

### ISSUE THREAD

**Issue by satish28** [Dineshs91/devlog#15]
An user needs to find out by Trial and Error that he has to use a "," to separate multiple tags. It will be better if we use ";" and may be give a hint of which is a valid separator to the user when he is typing in tags.

**Comment by Dineshs91** [comment]
For now updating the readme, to reflect the same. (Comma as tag seperator)

**Comment by Dineshs91** [comment]
Added tooltip for tags, which displays the tag seperator

**Comment by Dineshs91** [comment]
This won't be an issue in the next version. Stay tuned !
