### ISSUE TITLE
Can an editor be used ?

### ISSUE THREAD

**Issue by Dineshs91** [Dineshs91/devlog#27]
Have a look at [Trix](http://trix-editor.org/)

[source](https://github.com/basecamp/trix)

**Comment by avinasha** [comment]
There are few options here. The editor was a major point of discussion when I was at http://supportbee.com 

##### What we used
- Started with https://www.tinymce.com/ . Pros: Nice community,  Cons: Heavy
- Moved to https://imperavi.com/redactor/. Pros: Lighter than TinyMCE. Cons: Bad codebase. Bad support. Breaks for heavy usage
- Finally used http://ckeditor.com/. Pros: Lighter than TinyMCE. Doesnt have the problems of Redactor

**Comment by Dineshs91** [comment]
Thanks for the suggestions.

I had already tried tinymce and ckeditor, even I found ckeditor better than tinymce.

**Comment by Dineshs91** [comment]
[Substance](https://github.com/substance/substance) Js content editor.

**Comment by Dineshs91** [comment]
Using [angular-trix](https://github.com/sachinchoolur/angular-trix) and [trix](http://trix-editor.org/)
